apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: varlog
              mountPath: /log
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
