apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: busybox
          image: busybox
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: data
              mountPath: /data
          command:
            [
              "sh",
              "-c",
              "echo 'start busybox' && while true; do date > /data/logs/myapp.txt; sleep 5; done",
            ]
        - name: multitool
          image: praqma/network-multitool
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: data
              mountPath: /data
          command:
            [
              "sh",
              "-c",
              "echo 'start multitool' && while true; do cat /data/logs/myapp.txt; sleep 5; done",
            ]
      initContainers:
        - name: delay
          image: busybox
          command:
            [
              "sh",
              "-c",
              "echo 'creating dir' && mkdir -p /data/logs && echo 'creating file' && touch /data/logs/myapp.txt",
            ]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
