apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc
      containers:
        - name: nginx
          image: nginx:1.25
          volumeMounts:
            - name: my-volume
              mountPath: /static
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
