apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    name: echoserver
spec:
  containers:
    - name: echoserver
      image: ealen/echo-server:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
