apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      initContainers:
        - name: delay
          image: busybox
          command: ["sleep", "60"]
