apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-cm-nginx
data:
  index.html: |
    <html>
      <head>
          <title>Example</title>
      </head>
      <body>
          <p>This is an example of a simple HTML page with one paragraph.</p>
      </body>
    </html>
