apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: myapp
  ports:
    - port: 9001
      targetPort: 80
      name: nginx
    - port: 9002
      targetPort: 8080
      name: multitool
